---
server:
  port: 8888
  error:
    whitelabel:
      #To switch the default error page off
      enabled: false
spring: 
  application:
    name: ms-infra-oauthclient
  profiles: 
    active: ${spring.profiles.active} 
---
spring:
  profiles: localhost
logging: 
  file: /opt/ms/INFRA/logs/ms-infra-oauthclient.log
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
    console: "%d %-5level [%thread] %logger : %msg%n"
  level: 
    com.om.infra.oauth: DEBUG
    org.springframework: ERROR
    org.springframework.boot.env.PropertySourcesLoader: ERROR
    org.springframework.boot.autoconfigure.security: TRACE
    org.springframework.boot.web: ERROR
    org.springframework.boot.web.embedded: ERROR
    org.springframework.cloud: ERROR
    org.springframework.web: ERROR
    org.springframework.beans: ERROR
    org.springframework.test: DEBUG
    org.springframework.security: TRACE
    org.thymeleaf: ERROR
    org.eclipse.jetty: ERROR
---
spring:
  profiles: development,stage,production,cloud
logging:
  pattern: 
    console: "%d %-5level [%thread] %logger : %msg%n"
  level: 
    com.om.infra.oauth: WARN
    org.springframework: ERROR
    org.springframework.boot.env.PropertySourcesLoader: ERROR
    org.springframework.boot.autoconfigure.security: ERROR
    org.springframework.boot.web: ERROR
    org.springframework.boot.web.embedded: WARN
    org.springframework.cloud: ERROR
    org.springframework.web: ERROR
    org.springframework.beans: ERROR
    org.springframework.test: DEBUG
    org.springframework.security: TRACE
    org.thymeleaf: ERROR
    org.eclipse.jetty: WARN      